style_edition = "2024"
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
reorder_modules = true
