[package]
name = "zirael_utils"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Zirael Utils"

[dependencies]
anstyle = { workspace = true }
ariadne = { workspace = true }
clap = { workspace = true }
id-arena = { workspace = true }
lasso = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
colored = { workspace = true }
fs-err = { workspace = true }
rayon = { workspace = true }
env_logger = { workspace = true }

[lints]
workspace = true
