[package]
name = "zirael_parser"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
unicode-xid = "0.2.6"
unicode-normalization = "0.1.25"
zirael_utils = { workspace = true }

[lints]
workspace = true
